// Generated by CoffeeScript 1.3.3

$(document).ready(function() {
  var formtip,
    _this = this;
  $('.effs').p2acc({
    autoStart: true,
    slideInterval: 5000,
    slideNum: false
  });
  $('#header select').each(function(index, element) {
    var ele, title;
    ele = $(element);
    ele.parent().addClass('select');
    title = $('option:selected', ele).text();
    title || (title = $('option:first', ele).text());
    return ele.css({
      'z-index': 10,
      'opacity': 0
    }).after('<span>' + title + '</span>').change(function() {
      title = $('option:selected', ele).text();
      return ele.next().text(title);
    });
  });
  $('#search .container').tabs();
  $('#check_all').change(function() {
    var checked, _ref;
    checked = (_ref = $('#check_all:checked').length) != null ? _ref : {
      "true": false
    };
    if (checked) {
      return $(this).parents('table').find('td input').attr('checked', true);
    } else {
      return $(this).parents('table').find('td input').removeAttr('checked');
    }
  });
  $('#doitac li').each(function(index, element) {
    var ele, img, imgsrc;
    ele = $(element);
    img = $('img', ele);
    imgsrc = img.attr('src').replace('.', '-bw.');
    ele.css({
      'background': 'url(' + imgsrc + ')'
    });
    return img.hover((function() {
      return $(this).addClass("hover");
    }, function() {
      return $(this).remove("hover");
    }));
  });
  $('.jslider').each(function() {
    var current, currentPos, filler, slider, step, tooltip, total;
    slider = $(this);
    filler = $('.filler', slider);
    tooltip = $('.tooltip', slider);
    tooltip.css({
      'margin-left': -tooltip.width() / 2
    });
    total = slider.attr('total');
    current = slider.attr('current');
    step = slider.width() / total;
    currentPos = step * current;
    return filler.width(currentPos);
  });
  formtip = $('.formtip');
  formtip.each(function(index, tip) {
    var $tip, text, title;
    $tip = $(tip);
    text = $tip.attr('placeholder');
    title = $tip.attr('title');
    $tip.attr('placeholder', '');
    $('<a />').addClass('questiontip right').insertAfter($tip).text('?').attr('title', title).attr('tipcontents', text);
    return $tip.next('a.questiontip').qtip({
      position: {
        my: 'bottom left',
        at: 'top center'
      },
      content: {
        text: function(api) {
          return $(this).attr('tipcontents');
        },
        title: {
          text: title
        }
      },
      style: {
        classes: 'ui-tooltip-blue'
      }
    });
  });
  $('cbSalary').change(function() {
    return changeSalary();
  });
  $('table').on('click', 'input:checkbox', function(e) {
    var etarget, otherInput, target;
    etarget = $(e.target);
    target = etarget.attr('class') + ' ' + etarget.attr('id') + ' ' + etarget.attr('rel');
    if ((target.indexOf('check_all') >= 0) && (etarget.parent('th').length > 0)) {
      otherInput = $(e.delegateTarget).find('td input:checkbox');
      if (etarget.is(':checked')) {
        return otherInput.attr('checked', 'checked');
      } else {
        return otherInput.removeAttr('checked');
      }
    }
  });
  return $('.search-cate').masonry({
    itemSelector: '.cate'
  });
});
